### ISSUE TITLE
Alignbench score looks abnormal

### ISSUE THREAD

**Issue by 2024WY** [open-compass/CompassJudger#4]
Use CompassJudger-1 to Test qwen2.5 3b model on Subjective Datasets,but Alignbench score looks abnormal，the total score is only 5.52，but in compassjudger_subj_eval_leaderboard is 55.2:

Alignbench | 总分 | 5.52 |  
Alignbench | 专业能力 | 5.56 |  
Alignbench | 数学计算 | 5.92 |  
Alignbench | 基本任务 | 5.6 |  
Alignbench | 逻辑推理 | 4.49 |  
Alignbench | 文本写作 | 5.89 |  
Alignbench | 中文理解 | 5.86 |  
Alignbench | 角色扮演 | 5.91 |  
Alignbench | 综合问答 | 6.29 |  
AlpacaEval | total | 32.05 |  
AlpacaEval | helpful_base | 18.6 |  
AlpacaEval | koala | 26.92 |  
AlpacaEval | oasst | 33.51 |  
AlpacaEval | selfinstruct | 38.1 |  
AlpacaEval | vicuna | 41.25 |  
ArenaHard | score | 40.81 |  

Below is my eval_subjective.py, I run  ”python run.py configs/eval_subjective.py“,Can you give some advice?

from mmengine.config import read_base
with read_base():
    from opencompass.configs.datasets.subjective.alignbench.alignbench_judgeby_critiquellm import alignbench_datasets
    from opencompass.configs.datasets.subjective.alpaca_eval.alpacav2_judgeby_gpt4 import alpacav2_datasets
    from opencompass.configs.datasets.subjective.compassarena.compassarena_compare import compassarena_datasets
    from opencompass.configs.datasets.subjective.arena_hard.arena_hard_compare import arenahard_datasets
    from opencompass.configs.datasets.subjective.compassbench.compassbench_compare import compassbench_datasets
    from opencompass.configs.datasets.subjective.fofo.fofo_judge import fofo_datasets
    from opencompass.configs.datasets.subjective.wildbench.wildbench_pair_judge import wildbench_datasets
    from opencompass.configs.datasets.subjective.multiround.mtbench_single_judge_diff_temp import mtbench_datasets
    from opencompass.configs.datasets.subjective.multiround.mtbench101_judge import mtbench101_datasets
from opencompass.models import HuggingFaceCausalLM, HuggingFace, HuggingFaceChatGLM3, TurboMindModelwithChatTemplate, HuggingFacewithChatTemplate
from opencompass.partitioners import NaivePartitioner, SizePartitioner
from opencompass.partitioners.sub_naive import SubjectiveNaivePartitioner
from opencompass.partitioners.sub_size import SubjectiveSizePartitioner
from opencompass.partitioners.sub_num_worker import SubjectiveNumWorkerPartitioner
from opencompass.runners import LocalRunner
from opencompass.runners import SlurmSequentialRunner
from opencompass.tasks import OpenICLInferTask
from opencompass.tasks.subjective_eval import SubjectiveEvalTask
from opencompass.summarizers import SubjectiveSummarizer

api_meta_template = dict(
    round=[
        dict(role='HUMAN', api_role='HUMAN'),
        dict(role='BOT', api_role='BOT', generate=True),
    ]
)

# -------------Inference Stage ----------------------------------------
# For subjective evaluation, we often set do sample for models
models = [
    dict(
        type=HuggingFacewithChatTemplate,
        abbr='Qwen2.5-3B-Instruct',
        path='/models/Qwen/Qwen2.5-3B-Instruct',
        tokenizer_path='/models/Qwen/Qwen2.5-3B-Instruct',
        model_kwargs=dict(
            device_map='auto',
            trust_remote_code=True,
        ),
        tokenizer_kwargs=dict(
            padding_side='left',
            truncation_side='left',
            trust_remote_code=True,
        ),
        generation_kwargs=dict(
            do_sample=True, #For subjective evaluation, we suggest you do set do_sample when running model inference!
        ),
        meta_template=api_meta_template,
        max_out_len=2048,
        max_seq_len=4096,
        batch_size=8,
        run_cfg=dict(num_gpus=1, num_procs=1),
    )
]

datasets = [*alignbench_datasets, *alpacav2_datasets, *arenahard_datasets] # add datasets you want

infer = dict(
    partitioner=dict(type=NaivePartitioner),
    runner=dict(type=LocalRunner, max_num_workers=4, task=dict(type=OpenICLInferTask)),
)
# -------------Evalation Stage ----------------------------------------

judge_models = [dict(
        type=TurboMindModelwithChatTemplate,
        abbr='CompassJudger-1-7B-Instruct',
        path='/opencompass/model/CompassJudger-1-7B-Instruct',
        meta_template=api_meta_template,
        engine_config=dict(session_len=16384, max_batch_size=8, tp=1),
        gen_config=dict(top_k=1, temperature=1e-6, top_p=0.9, max_new_tokens=2048),
        max_seq_len=16384,
        max_out_len=2048,
        batch_size=8,
        run_cfg=dict(num_gpus=1),
    )]

## ------------- Evaluation Configuration
eval = dict(
    partitioner=dict(type=SubjectiveNaivePartitioner, models=models, judge_models=judge_models,),
    runner=dict(type=LocalRunner, max_num_workers=4, task=dict(type=SubjectiveEvalTask)),
)

summarizer = dict(type=SubjectiveSummarizer, function='subjective')
work_dir = 'outputs/subjective/'

**Comment by bittersweet1999** [comment]
Hi, both scores you mentioned are correct. The score directly obtained using the official code for AlignBench should be between 0-10, which is consistent with the official scores of AlignBench. In the compassjudger_subj_eval_leaderboard, in order to calculate the average score when combined with other subjective evaluation datasets, we converted the scores of all datasets to a percentage scale. Therefore, the AlignBench score was multiplied by 10.
